import { ThemeConfig } from '../types';

/**
 * Inkwell (文艺复古) 主题配置
 */
export const inkwellTheme: ThemeConfig = {
  id: 'inkwell',
  name: 'Inkwell',
  description: '文艺复古风格，适合文学、艺术类博客',
  version: '2.0.0',
  author: 'Blog Platform',
  thumbnail: '/themes/inkwell/preview.png',
  isDefault: true,
  regions: ['header', 'footer', 'sidebar', 'main', 'article'],
  settings: {
    primaryColor: '#1A2456',
    secondaryColor: '#5D4037',
    accentColor: '#B71C1C',
    backgroundColor: '#F5F2E9',
    textColor: '#1A2456',
    fontFamily: "'Inter', 'Playfair Display', serif",
    borderRadius: 'md',
    shadowStyle: 'md',
    layoutWidth: 'wide',
    animations: true,
    custom: {
      showDecorativeElements: true,
      useSerifFonts: true,
      vintageStyle: true,
    },
  },
  colorSchemes: [
    {
      name: 'Light',
      id: 'light',
      isDark: false,
      cssVariables: {
        '--theme-primary': '#1A2456',
        '--theme-primary-light': '#2a3a7a',
        '--theme-primary-dark': '#0f1740',
        '--theme-secondary': '#5D4037',
        '--theme-accent': '#B71C1C',
        '--theme-accent-hover': '#d32f2f',
        '--theme-bg': '#F5F2E9',
        '--theme-bg-alt': '#EDE8D8',
        '--theme-bg-card': '#F5F2E9',
        '--theme-surface': '#FFFFFF',
        '--theme-text': '#1A2456',
        '--theme-text-muted': 'rgba(26, 36, 86, 0.7)',
        '--theme-border': '#E8DCCA',
        '--theme-radius-card': '0.5rem',
        '--theme-radius-button': '0.375rem',
        '--theme-nav-bg': 'rgba(245, 242, 233, 0.9)',
        '--theme-hero-gradient': 'linear-gradient(135deg, rgba(26, 36, 86, 0.05) 0%, rgba(245, 242, 233, 0) 100%)',
        '--theme-card-shadow': '0 10px 25px -5px rgba(0, 0, 0, 0.05), 0 8px 10px -6px rgba(0, 0, 0, 0.02)',
        '--theme-card-shadow-hover': '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
        '--theme-glow': 'none',
        '--theme-gradient-accent': 'linear-gradient(135deg, #B71C1C, #d32f2f)',
      },
    },
    {
      name: 'Dark',
      id: 'dark',
      isDark: true,
      cssVariables: {
        '--theme-primary': '#2a3a7a',
        '--theme-primary-light': '#3a4a8a',
        '--theme-primary-dark': '#1a2a6a',
        '--theme-secondary': '#6D5047',
        '--theme-accent': '#C72C2C',
        '--theme-accent-hover': '#e33f3f',
        '--theme-bg': '#1a1820',
        '--theme-bg-alt': '#252330',
        '--theme-bg-card': '#1e1c28',
        '--theme-surface': '#2d2b38',
        '--theme-text': '#E8E4D9',
        '--theme-text-muted': 'rgba(232, 228, 217, 0.6)',
        '--theme-border': '#3d3850',
        '--theme-radius-card': '0.5rem',
        '--theme-radius-button': '0.375rem',
        '--theme-nav-bg': 'rgba(26, 24, 32, 0.9)',
        '--theme-hero-gradient': 'linear-gradient(135deg, rgba(42, 58, 122, 0.1) 0%, rgba(26, 24, 32, 0) 100%)',
        '--theme-card-shadow': '0 10px 25px -5px rgba(0, 0, 0, 0.3), 0 8px 10px -6px rgba(0, 0, 0, 0.2)',
        '--theme-card-shadow-hover': '0 20px 25px -5px rgba(0, 0, 0, 0.4), 0 10px 10px -5px rgba(0, 0, 0, 0.3)',
        '--theme-glow': 'none',
        '--theme-gradient-accent': 'linear-gradient(135deg, #C72C2C, #e33f3f)',
      },
    },
  ],
  components: [
    'Header',
    'Footer',
    'Sidebar',
    'ArticleCard',
    'HeroSlider',
  ],
};

export default inkwellTheme;
